### ISSUE TITLE
TypeError: cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by woehrer12** [woehrer12/TBpolo#1]
https://github.com/woehrer12/TBpolo/blob/eb940a37c75fe19011d69d140a8e9822fe2e0270/Codes/Pipeline_I_to_III.py#L216

  File "/home/*/TBpolo/Codes/Pipeline_I_to_III.py", line 233, in <module>
    pk.dump(classifier, open("./Models/DL_model_{}PC_stoploss{}_takeprofit{}.pkl".format(nPCs, stoploss, takeprofit),"wb"))
TypeError: cannot pickle 'weakref' object

**Comment by saas-coder** [comment]
Pickle  can't serialize keras, You can save the weights of model using the following line
`
classifer.save_weights('model.h5')`
